### ISSUE TITLE
fannj invalid memory access

### ISSUE THREAD

**Issue by seidlmatus** [krenfro/fannj#9]
Can you help me with my problem, I can't finish school projekt, thanks you for quickly help

http://stackoverflow.com/questions/39924143/fannj-invalid-memory-access

**Comment by krenfro** [comment]
Please provide a bit of information on the following:

What version of FANN are you using?
What version of FANNJ are you using?
What version of JNA are you using?
Did you set LD_LIBRARY_PATH and jna.library.path as described in project readme?

**Comment by seidlmatus** [comment]
sorry, that is my error your code is OK,
